name: Build and Push Docker Images

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build up-to-date CentOS 7 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: updated
          tags: ${{ secrets.DOCKER_USERNAME }}/centos:7-updated
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/centos:7-updated
          cache-to: type=inline

      - name: Build pyenv image from centos:7-updated
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: pyenv
          tags: ${{ secrets.DOCKER_USERNAME }}/pyenv:latest-centos7
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/pyenv:latest-centos7
          cache-to: type=inline

      - name: Build python 3.11 image from pyenv:latest-centos7
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: python311
          tags: ${{ secrets.DOCKER_USERNAME }}/python:3.11-centos7
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/python:3.11-centos7
          cache-to: type=inline
